# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-15 18:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_Add_user_id_to_events'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='user',
            new_name='manager',
        ),
    ]
