# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-10 17:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('position', '0005_CHANGED_ONETOONE_TO_MANYTOONE_MANAGER'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=60)),
                ('phone_num', models.CharField(max_length=12)),
                ('birth_date', models.CharField(max_length=11)),
                ('status', models.CharField(max_length=140)),
                ('isManager', models.BooleanField(default=False)),
                ('position', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='position.Position')),
            ],
        ),
    ]
