# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-10 17:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0001_CHANGED_PROFIL_MODEL_POSITION_NULL'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='isManager',
            new_name='ismanager',
        ),
    ]
