# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-20 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0001_Profile_Model_Added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.CharField(max_length=11),
        ),
    ]
