# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-24 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0002_MODIFIED PROFILE MODEL WITH CASCADE AND STRING DATE'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.CharField(default='one-off default', max_length=60),
            preserve_default=False,
        ),
    ]
