# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-29 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='department',
            field=models.CharField(default='Main', max_length=100),
        ),
        migrations.AlterField(
            model_name='position',
            name='hourly_salary',
            field=models.FloatField(),
        ),
    ]
