# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-06 15:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0004_CHANGED_POSITION_ATTR_NAMES'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
