# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-22 20:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('hours', models.FloatField(default=0.0)),
                ('taken_shifts', models.IntegerField(default=0)),
                ('given_shifts', models.IntegerField(default=0)),
                ('total', models.FloatField(default=0)),
            ],
        ),
    ]
