# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-25 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_CREATED STAT MODEL'),
    ]

    operations = [
        migrations.AddField(
            model_name='stat',
            name='shifts',
            field=models.IntegerField(default=0),
        ),
    ]
