# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-19 21:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shift_replace', '0001_Create_shift_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shift',
            old_name='shift',
            new_name='event',
        ),
    ]
