# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-19 21:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shift_replace', '0002_Rename_shift_col_to_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.Event'),
        ),
    ]
