# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-26 23:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rewards', '0001_CREATED_REWARD_MODEL'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_Rewards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rewards.Reward')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='employee_rewards',
            unique_together=set([('reward', 'employee')]),
        ),
    ]
