# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-10 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_Add organization model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='organization_name',
            field=models.TextField(unique=True),
        ),
    ]
